# Prefer domestic binary caches first, then fall back to the official cache.
substituters = https://mirrors.ustc.edu.cn/nix-channels/store https://mirror.sjtu.edu.cn/nix-channels/store https://cache.nixos.org/
experimental-features = nix-command flakes
