set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:Tc"


set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g escape-time 0
set -g history-limit 10000

set -g default-terminal "xterm-256color"
set -as terminal-overrides ",xterm-256color:Tc"

bind-key q confirm-before -p "杀掉面板 #P? (y/n)" kill-pane
bind-key Q confirm-before -p "杀掉整个会话? (y/n)" kill-session

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R


set -g status-style "bg=#1e1e2e,fg=#cdd6f4"
set -g status-left-length 120
set -g status-left "❐ Session: #S "
set -g status-right "#[fg=#fab387,bold] %H:%M "
setw -g window-status-current-format "#[fg=#1e1e2e,bg=#89b4fa,bold] #I:#W #[default]#[fg=#f9e2af,bold]#{?#{==:#{client_prefix},1}, =>,}#[fg=#cdd6f4]#{?#{==:#{client_prefix},1}, S save | R restore | b lock | Q quit,}#[default] "
setw -g window-status-format "#[fg=#9399b2] #I:#W "
set -g pane-border-style "fg=#585b70"
set -g pane-active-border-style "fg=#89b4fa,bg=#313244"




# Lock Toggle
bind b \
    set prefix None \;\
    set key-table off \;\
    set status-style "bg=#444444,fg=#888888" \;\
    set status-left "#[fg=#ff5555,bold] 🔒 LOCKED " \;\
    if -F '#{pane_in_mode}' 'send-keys -X cancel' \;\
    refresh-client -S

bind -T off b \
    set -u prefix \;\
    set -u key-table \;\
    set -u status-style \;\
    set -u status-left \;\
    refresh-client -S

set -as terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[2 q'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Change resurrect save key to avoid C-s flow control issues
set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '10'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
